import fs from "fs";
import path from "path";

const buildInfoFile = path.resolve("./src/buildInfo.ts");

// Format lisible : "dev 2026-01-26 15:42"
const now = new Date();
const pad = (n) => String(n).padStart(2, "0");

const buildTime =
  "dev " +
  `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ` +
  `${pad(now.getHours())}:${pad(now.getMinutes())}`;

const content =
  `// AUTO-GENERATED by tools/bump-version.mjs (dev)\n` +
  `export const BUILD_TIME = "${buildTime}";\n` +
  `export const BUILD_HASH = "";\n`;

fs.writeFileSync(buildInfoFile, content, "utf-8");

console.log(`[bump-version] buildInfo.ts updated: ${buildTime}`);
